// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```



class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzmuc2vKvYFUJIedS5RclBWdhd3ZD2X6E',
    appId: '1:464644665028:web:1c4ebda8649ceb9dcc6391',
    messagingSenderId: '464644665028',
    projectId: 'telme-app',
    authDomain: 'telme-app.firebaseapp.com',
    storageBucket: 'telme-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxU2sRSUV4IbiHpjqJhAaGzRQDhklpySk',
    appId: '1:464644665028:android:22ab7d573eff9746cc6391',
    messagingSenderId: '464644665028',
    projectId: 'telme-app',
    storageBucket: 'telme-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu_CbQXh9Ieyi5O7Ymbc4sd7bD7ViuWXg',
    appId: '1:464644665028:ios:f0c4fffa4d9f9aaccc6391',
    messagingSenderId: '464644665028',
    projectId: 'telme-app',
    storageBucket: 'telme-app.appspot.com',
    iosBundleId: 'com.example.telme',
  );
}
